"use client";

import { useState } from "react";
import {
  eventSummary,
  barangayRiskScores,
  aidPrioritization,
  dataSources,
  recommendations,
} from "@/data/disaster-report";
import {
  FileText,
  AlertTriangle,
  Database,
  Lightbulb,
  ShieldAlert,
  Clock,
  MapPin,
  MessageSquare,
  Radio,
  Zap,
  TrendingUp,
  ChevronDown,
  ChevronUp,
} from "lucide-react";

const priorityConfig: Record<
  string,
  { color: string; bg: string; icon: string }
> = {
  Critical: { color: "text-red-700", bg: "bg-red-50 border-red-200", icon: "🔴" },
  High: { color: "text-orange-700", bg: "bg-orange-50 border-orange-200", icon: "🟠" },
  Moderate: { color: "text-amber-700", bg: "bg-amber-50 border-amber-200", icon: "🟡" },
  Low: { color: "text-green-700", bg: "bg-green-50 border-green-200", icon: "🟢" },
};

const INITIAL_SHOWN = 5;

export default function PostDisasterReport() {
  const [showAll, setShowAll] = useState(false);

  const displayedRows = showAll
    ? barangayRiskScores
    : barangayRiskScores.slice(0, INITIAL_SHOWN);

  return (
    <div className="min-h-full">
      {/* Header */}
      <div className="px-4 sm:px-8 py-6 border-b border-border bg-white">
        <div className="flex items-center gap-2 mb-1">
          <FileText size={18} className="text-primary" />
          <span className="text-xs font-medium uppercase tracking-wide text-primary">
            Post-Disaster Assessment
          </span>
        </div>
        <h1 className="text-xl font-semibold text-text-primary">
          Flash Flood Event — March 15, 2026
        </h1>
        <p className="text-sm text-text-secondary mt-1">
          Automated report generated by DigiTALINO DRRM Module
        </p>
      </div>

      <div className="p-4 sm:p-8 space-y-6 max-w-6xl">
        {/* Event Summary Card */}
        <div className="bg-white border border-border rounded">
          <div className="px-4 sm:px-6 py-4 border-b border-border">
            <h2 className="font-semibold text-text-primary flex items-center gap-2">
              <ShieldAlert size={16} />
              Event Summary
            </h2>
          </div>
          <div className="p-4 sm:p-6">
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4 sm:gap-6">
              <SummaryItem
                icon={<Zap size={14} />}
                label="Event Type"
                value={eventSummary.eventType}
              />
              <SummaryItem
                icon={<Clock size={14} />}
                label="Date & Duration"
                value={eventSummary.date}
                sub={eventSummary.duration}
              />
              <SummaryItem
                icon={<MapPin size={14} />}
                label="Affected Barangays"
                value={eventSummary.affectedBarangays}
              />
              <SummaryItem
                icon={<MessageSquare size={14} />}
                label="Citizen Reports"
                value={String(eventSummary.totalReports)}
                sub={`${eventSummary.classifiedByNlp} classified (${eventSummary.classificationRate})`}
              />
              <SummaryItem
                icon={<AlertTriangle size={14} />}
                label="Unclassified"
                value={`${eventSummary.unclassified} (routed to manual review)`}
              />
              <SummaryItem
                icon={<Radio size={14} />}
                label="SMS Alerts Dispatched"
                value={eventSummary.smsAlertsDispatched}
              />
              <SummaryItem
                icon={<TrendingUp size={14} />}
                label="Sensor Triggers"
                value={eventSummary.sensorTriggers}
              />
            </div>
          </div>
        </div>

        {/* Section 1: Barangay Risk Scores */}
        <div className="bg-white border border-border rounded">
          <div className="px-4 sm:px-6 py-4 border-b border-border">
            <h2 className="font-semibold text-text-primary flex items-center gap-2">
              <AlertTriangle size={16} />
              Barangay Risk Scores
            </h2>
            <p className="text-xs text-text-muted mt-1">
              Updated risk assessment based on aggregated event data
            </p>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-sm min-w-[800px]">
              <thead>
                <tr className="border-b border-border bg-surface">
                  <th className="text-left px-4 py-3 font-medium text-text-secondary text-xs uppercase tracking-wide">Rank</th>
                  <th className="text-left px-4 py-3 font-medium text-text-secondary text-xs uppercase tracking-wide">Barangay</th>
                  <th className="text-left px-4 py-3 font-medium text-text-secondary text-xs uppercase tracking-wide">Risk Score</th>
                  <th className="text-left px-4 py-3 font-medium text-text-secondary text-xs uppercase tracking-wide">Sensor Alerts</th>
                  <th className="text-left px-4 py-3 font-medium text-text-secondary text-xs uppercase tracking-wide">Citizen Reports</th>
                  <th className="text-left px-4 py-3 font-medium text-text-secondary text-xs uppercase tracking-wide">Dominant Hazard</th>
                  <th className="text-right px-4 py-3 font-medium text-text-secondary text-xs uppercase tracking-wide">Households</th>
                  <th className="text-left px-4 py-3 font-medium text-text-secondary text-xs uppercase tracking-wide">Aid Priority</th>
                </tr>
              </thead>
              <tbody>
                {displayedRows.map((row) => {
                  const pConfig = priorityConfig[row.aidPriority];
                  return (
                    <tr
                      key={row.rank}
                      className="border-b border-border last:border-0 hover:bg-surface/50"
                    >
                      <td className="px-4 py-3 text-text-muted font-mono text-xs">{row.rank}</td>
                      <td className="px-4 py-3 font-medium text-text-primary">{row.barangay}</td>
                      <td className="px-4 py-3">
                        <div className="flex items-center gap-2">
                          <div className="w-16 h-2 bg-surface rounded overflow-hidden">
                            <div
                              className={`h-full rounded ${
                                row.riskScore >= 75
                                  ? "bg-red-500"
                                  : row.riskScore >= 50
                                  ? "bg-orange-400"
                                  : row.riskScore >= 25
                                  ? "bg-amber-400"
                                  : "bg-green-400"
                              }`}
                              style={{ width: `${row.riskScore}%` }}
                            />
                          </div>
                          <span className="text-xs font-mono text-text-secondary">
                            {row.riskScore} / {row.maxScore}
                          </span>
                        </div>
                      </td>
                      <td className="px-4 py-3 text-text-secondary text-xs">{row.sensorAlerts}</td>
                      <td className="px-4 py-3 text-text-secondary text-xs">{row.citizenReports}</td>
                      <td className="px-4 py-3 text-text-secondary text-xs">{row.dominantHazard}</td>
                      <td className="px-4 py-3 text-right text-text-secondary text-xs font-mono">
                        {row.householdsAffected.toLocaleString()}
                      </td>
                      <td className="px-4 py-3">
                        <span
                          className={`inline-flex items-center gap-1 text-[11px] font-medium px-2 py-0.5 rounded border ${pConfig.bg} ${pConfig.color}`}
                        >
                          {pConfig.icon} {row.aidPriority}
                        </span>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          {/* Show All / Show Less toggle */}
          {barangayRiskScores.length > INITIAL_SHOWN && (
            <div className="border-t border-border">
              <button
                onClick={() => setShowAll(!showAll)}
                className="w-full flex items-center justify-center gap-2 px-4 py-3 text-xs font-medium text-text-secondary hover:text-primary hover:bg-surface transition-colors"
              >
                {showAll ? (
                  <>
                    <ChevronUp size={14} />
                    Show fewer barangays
                  </>
                ) : (
                  <>
                    <ChevronDown size={14} />
                    Show all {barangayRiskScores.length} barangays
                    <span className="text-text-muted">
                      ({barangayRiskScores.length - INITIAL_SHOWN} more)
                    </span>
                  </>
                )}
              </button>
            </div>
          )}

          <div className="px-4 sm:px-6 py-3 bg-surface border-t border-border">
            <p className="text-xs text-text-muted leading-relaxed">
              Risk scores are computed from sensor threshold breaches (30%),
              citizen report density and urgency (40%), and historical flood
              incidence data (30%). Scores update automatically after each
              disaster event.
            </p>
          </div>
        </div>

        {/* Section 2: Aid Delivery Prioritization */}
        <div className="bg-white border border-border rounded">
          <div className="px-4 sm:px-6 py-4 border-b border-border">
            <h2 className="font-semibold text-text-primary flex items-center gap-2">
              <TrendingUp size={16} />
              Aid Delivery Prioritization
            </h2>
            <p className="text-xs text-text-muted mt-1">
              Recommended order for relief distribution based on computed risk scores
            </p>
          </div>
          <div className="p-4 sm:p-6 space-y-3">
            {aidPrioritization.map((item, i) => {
              const pConfig = priorityConfig[item.priority];
              const maxHouseholds = 1240;
              const barWidth = (item.households / maxHouseholds) * 100;
              return (
                <div
                  key={item.barangay}
                  className={`border rounded p-4 ${pConfig.bg}`}
                >
                  <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 mb-2">
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-bold text-text-muted">{i + 1}.</span>
                      <span className={`text-xs font-semibold px-2 py-0.5 rounded ${pConfig.bg} ${pConfig.color}`}>
                        {pConfig.icon} {item.priority}
                      </span>
                      <span className="text-sm font-medium text-text-primary">{item.barangay}</span>
                    </div>
                    <span className="text-xs font-mono text-text-secondary">
                      {item.households.toLocaleString()} households
                    </span>
                  </div>
                  <div className="w-full h-1.5 bg-white/80 rounded overflow-hidden mb-2">
                    <div
                      className={`h-full rounded ${
                        item.priority === "Critical"
                          ? "bg-red-400"
                          : item.priority === "High"
                          ? "bg-orange-400"
                          : item.priority === "Moderate"
                          ? "bg-amber-400"
                          : "bg-green-400"
                      }`}
                      style={{ width: `${barWidth}%` }}
                    />
                  </div>
                  <p className="text-xs text-text-secondary">
                    <span className="font-medium">Recommended:</span>{" "}
                    {item.recommendation}
                  </p>
                </div>
              );
            })}
          </div>
          <div className="px-4 sm:px-6 py-3 bg-surface border-t border-border">
            <p className="text-xs text-text-muted leading-relaxed">
              This prioritization replaces the previous manual assessment
              process, where aid distribution relied on verbal reports and
              delayed field surveys. With DigiTALINO, the DRRMO can begin
              dispatching aid within minutes of an event&apos;s conclusion.
            </p>
          </div>
        </div>

        {/* Section 3: Recommendations */}
        <div className="bg-white border border-border rounded">
          <div className="px-4 sm:px-6 py-4 border-b border-border">
            <h2 className="font-semibold text-text-primary flex items-center gap-2">
              <Lightbulb size={16} />
              Recommendations for Next Event
            </h2>
            <p className="text-xs text-text-muted mt-1">
              System-generated recommendations based on post-event analysis
            </p>
          </div>
          <div className="p-4 sm:p-6">
            <div className="space-y-3">
              {recommendations.map((rec, i) => (
                <div
                  key={i}
                  className="flex gap-3 items-start px-4 py-3 bg-surface rounded border border-border"
                >
                  <span className="w-6 h-6 rounded-full bg-primary/10 flex items-center justify-center shrink-0 mt-0.5">
                    <span className="text-xs font-bold text-primary">{i + 1}</span>
                  </span>
                  <p className="text-sm text-text-primary leading-relaxed">{rec}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Section 4: Data Sources Summary */}
        <div className="bg-white border border-border rounded">
          <div className="px-4 sm:px-6 py-4 border-b border-border">
            <h2 className="font-semibold text-text-primary flex items-center gap-2">
              <Database size={16} />
              Data Sources Summary
            </h2>
          </div>
          <div className="p-4 sm:p-6">
            <div className="grid sm:grid-cols-2 gap-4">
              {dataSources.map((source) => (
                <div key={source.label} className="border border-border rounded p-4">
                  <div className="text-xs font-medium text-text-muted uppercase tracking-wide mb-1">
                    {source.label}
                  </div>
                  <div className="text-sm text-text-primary leading-relaxed">
                    {source.detail}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="text-center text-xs text-text-muted py-4 border-t border-border">
          Report generated automatically by DigiTALINO DRRM Module · CSCI_67 — IM Summit 2026 Demo
        </div>
      </div>
    </div>
  );
}

function SummaryItem({
  icon,
  label,
  value,
  sub,
}: {
  icon: React.ReactNode;
  label: string;
  value: string;
  sub?: string;
}) {
  return (
    <div>
      <div className="flex items-center gap-1.5 text-xs text-text-muted mb-1">
        {icon}
        {label}
      </div>
      <div className="text-sm font-medium text-text-primary">{value}</div>
      {sub && (
        <div className="text-xs text-text-secondary mt-0.5">{sub}</div>
      )}
    </div>
  );
}
